# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_release:
    environment: production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build
      run: |
         yarn
         npx tsc --outDir ./dist
         npx pkg --compress Gzip --out-path ./dist ./dist/bot.js
          
    - name: Zip file and calculate hash 
      run: |
           zip -r artifact ./dist
           echo "ZipHash=$(sha512sum artifact.zip)" >> $GITHUB_ENV
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: artifact.zip
        
    - name: Get tag name
      run: echo "TagName=$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_ENV
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          sha512-${{ env.ZipHash }}

          THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

          在適用法律允許的範圍內，對該程式沒有任何保證。除非另有書面說明，否則版權持有人和/或其他各方 "按原樣 "提供該程式，不提供任何明示或暗示的保證，包括但不限於對適銷性和特定用途的適用性的暗示保證。關於程式的品質和性能的全部風險由您承擔。如果該程式被證明有缺陷，您將承擔所有必要的服務、修理或糾正的費用。
        files: artifact.zip
        token: ${{ secrets.RELEASE_PAT }}
        tag_name: Build_${{ env.TagName }}
        prerelease: true
