# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_release:
    environment: production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build
      run: |
         npm ci
         npx tsc --outDir ./dist
         npx pkg --compress Gzip --out-path ./dist ./dist/bot.js
          
    - name: Zip file and calculate hash 
      run: |
           zip -r artifact ./dist
           echo "ZipHash=$(sha512sum artifact.zip)" >> $GITHUB_OUTPUT
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: release.zip
        
    - name: Get tag name
      run: echo "TagName=$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ env.ZipHash--sha512 }}
        files: artifact.zip
        token: ${{ secrets.RELEASE_PAT }}
        tag_name: Build_${{ env.TagName }}
        prerelease: true
